### ISSUE TITLE
Title of homepage shoes html tag

### ISSUE THREAD

**Issue by rh3xp** [lepisma/lepisma.github.io#11]
Your title of the homepage is showing the `<i> tag`

instead of (<i>car nil</i>) it is showing
`(<i>car nil</i>)`

mainly because of the html tag h1.
Please fix this issue.

**Comment by lepisma** [comment]
Should be fixed after https://github.com/lepisma/pile/commit/efa6efa17938205da9553d3a9bfc04ff2bd79b2b. Thanks for reporting!
