### ISSUE TITLE
Non-breaking hyphen not shown correctly in list view

### ISSUE THREAD

**Issue by parekhnish** [lepisma/lepisma.github.io#12]
The italicized part of the title: "Metaphysics‑of‑Quality" (for journal article dated 2018/07/18) has an issue being shown on the Journal Listing page, where the title shows up as "A Partial Interpretation of Metaphysics\342\200\221of\342\200\221Quality"

**Comment by lepisma** [comment]
https://github.com/lepisma/pile/issues/25

**Comment by lepisma** [comment]
Fixed.
